[App]
DEBUG = false
pitch = -16.800033569335938
yaw = 221.49684143066406
cameraPos = [4.1634912490844727,2.186596155166626,4.4259934425354004]
lightPos = [0.0,5.0,0.0]
lightColor = [1.0,1.0,1.0]
MarchingCubes = {threshold=0.5,detail=2}
[App.simulationSPH]
gridSize = [55,55,55]
gasStiffness = 100.0
heatCapacity = 4.1790000000000003
timeStep = 0.001
particleModel = "../resources/sphere.obj"
heatConductivity = 0.62
gridOrigin = [0.0,0.0,0.0]
fluidDensity = 998.28999999999996
viscosityCoefficient = 3.5
temperature = 100.0
fluidVolume = 4.0
datafiles = {}
Model = [
{particleModelOrigin=[0.0,0.0,0.0],particleModelSize=[30,30,31]},
]
[App.Evaporation]
coefficientA = 0.001
coefficientB = 0.0

[App.simulationGridFluid]
cellModel = "../resources/plane.obj"
specificGasConstant = 461.5
heatCapacity = 4.1790000000000003
buoyancyBeta = 0.10000000000000001
buoyancyAlpha = 9.8000000000000007
heatConductivity = 0.62
diffusionCoefficient = 0.001
ambientTemperature = 25.0
datafiles = {}

[Vulkan]
pathToShaders = "../shaders/"
window = {name="Fluid in tank (27K particles)",width=1280,height=720}

