[App]
DEBUG = false
pitch = -17.699899673461914
yaw = 1132.6715087890625
cameraPos = [-1.6957199573516846,2.5135376453399658,-3.7612974643707275]
lightPos = [0.0,5.0,0.0]
lightColor = [1.0,1.0,1.0]
MarchingCubes = {threshold=0.5,detail=2}
[App.simulationSPH]
viscosityCoefficient = 3.5
temperature = 100.0
gridSize = [20,20,20]
gasStiffness = 100.0
heatCapacity = 4.1790000000000003
timeStep = 0.001
fluidVolume = 2.0
particleModel = "../resources/sphere.obj"
heatConductivity = 0.62
gridOrigin = [0.0,0.0,0.0]
fluidDensity = 998.28999999999996
datafiles = {}
Model = [
{particleModelOrigin=[0.0,0.0,0.0],particleModelSize=[37,4,37]},
]
[App.Evaporation]
coefficientA = 0.001
coefficientB = 0.0

[App.simulationGridFluid]
cellModel = "../resources/plane.obj"
specificGasConstant = 461.5
heatCapacity = 4.1790000000000003
buoyancyBeta = 0.10000000000000001
buoyancyAlpha = 9.8000000000000007
heatConductivity = 0.62
diffusionCoefficient = 0.001
ambientTemperature = 25.0
datafiles = {}

[Vulkan]
pathToShaders = "../shaders/"
window = {name="Evaporation (5K Particles)",width=1280,height=720}

