[Vulkan]
pathToShaders = "../shaders/"
window = {height=720,width=1280,name="Fluid in tank (220K particles)"}
[App]
lightColor = [1.0,1.0,1.0]
lightPos = [0.0,5.0,0.0]
cameraPos = [0.49612230062484741,4.0091676712036133,5.800936222076416]
yaw = 284.19671630859375
pitch = -32.300075531005859
DEBUG = false
Evaporation = {coefficientB=0.0,coefficientA=0.001}
[App.simulationSPH]
fluidVolume = 4.0
temperature = 100.0
viscosityCoefficient = 3.5
fluidDensity = 998.28999999999996
gridOrigin = [0.0,0.0,0.0]
heatConductivity = 0.62
particleModel = "../resources/sphere.obj"
timeStep = 0.001
heatCapacity = 4.1790000000000003
gasStiffness = 100.0
gridSize = [110,40,34]
datafiles = {}
Model = [
{particleModelSize=[60,60,62],particleModelOrigin=[0.0,0.0,0.0]},
]
[App.MarchingCubes]
detail = 2
threshold = 0.5

[App.simulationGridFluid]
ambientTemperature = 25.0
diffusionCoefficient = 0.001
heatConductivity = 0.62
buoyancyAlpha = 9.8000000000000007
buoyancyBeta = 0.10000000000000001
heatCapacity = 4.1790000000000003
specificGasConstant = 461.5
cellModel = "../resources/plane.obj"
datafiles = {}


