[Vulkan]
pathToShaders = "/home/aka/CLionProjects/VulkanSPH/shaders/"
window = {height=720,width=1280,name="VulkanApp"}
[App]
lightColor = [1.0,1.0,1.0]
lightPos = [0.0,5.0,0.0]
cameraPos = [-0.80717611312866211,2.2152988910675049,2.8961858749389648]
yaw = 289.69686889648438
pitch = -32.300090789794922
outputToFile = true
DEBUG = true
Evaporation = {coefficientB=0.0,coefficientA=0.001}
[App.simulationSPH]
gridSize = [20,20,20]
gasStiffness = 10.0
heatCapacity = 4.1790000000000003
timeStep = 0.001
fluidVolume = 2.0
useNNS = true
particleCount = 27000
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"
heatConductivity = 0.62
gridOrigin = [0.0,0.0,0.0]
fluidDensity = 998.28999999999996
particleModelSize = [30,30,30]
viscosityCoefficient = 3.5
temperature = 100.0
datafiles = {}
[App.MarchingCubes]
detail = 2
threshold = 0.5

[App.simulationGridFluid]
ambientTemperature = 25.0
diffusionCoefficient = 0.001
heatConductivity = 0.62
buoyancyAlpha = 9.8000000000000007
buoyancyBeta = 0.10000000000000001
heatCapacity = 4.1790000000000003
specificGasConstant = 461.5
cellModel = "/home/aka/CLionProjects/VulkanSPH/resources/plane.obj"
datafiles = {}


