[App]
DEBUG = true

[App.simulation]
fluidVolume = 0.1
fluidDensity = 1000.0
particleCount = 512
particleModelSize = [8, 8, 8]
particleModel = "/home/kuro/CLionProjects/VulkanApp/resources/sphere.obj"

[Vulkan]

[Vulkan.window]
name = "VulkanApp"
width = 800
height = 600

[Vulkan.shaders]
vertex = "/home/kuro/CLionProjects/VulkanApp/shaders/shader.vert"
fragment = "/home/kuro/CLionProjects/VulkanApp/shaders/shader.frag"
compute.massDensity = "/home/kuro/CLionProjects/VulkanApp/shaders/SPH/MassDensity.comp"
compute.forces = "/home/kuro/CLionProjects/VulkanApp/shaders/SPH/Forces.comp"


