[App]
DEBUG = true
outputToFile = false

[App.simulationSPH]
useNNS = true
timeStep = 0.001
gasStiffness = 10.0
viscosityCoefficient = 3.5
fluidVolume = 0.2
fluidDensity = 998.29
particleCount = 8 #24000 #2304 #64
particleModelSize = [2,2,2] #[20,60,20] #[12, 16, 12] #[4, 4, 4]
gridOrigin =  [0.0, 0.0, 0.0]
gridSize = [3,3,3] #[40,40,40] #[8, 8, 8]
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"
heatConductivity = 0.62
heatCapacity = 4.179

[App.simulationGridFluid]
cellModel = "/home/aka/CLionProjects/VulkanSPH/resources/cube.obj"
ambientTemperature = 25.0

[Vulkan]
pathToShaders = "/home/aka/CLionProjects/VulkanSPH/shaders/"

[Vulkan.window]
name = "VulkanApp"
width = 1280
height = 720


