[App]
DEBUG = false
pitch = -35.800136566162109
yaw = 306.99868774414062
cameraPos = [-2.7610044479370117,3.4554340839385986,3.3099830150604248]
lightPos = [0.0,5.0,0.0]
lightColor = [1.0,1.0,1.0]
MarchingCubes = {threshold=0.5,detail=2}
Evaporation = {coefficientB=0.0,coefficientA=0.001}
[App.simulationSPH]
datafiles = []
gasStiffness = 10.0
gridSize = [20,20,20]
temperature = 100.0
viscosityCoefficient = 3.5
fluidDensity = 998.28999999999996
gridOrigin = [0.0,0.0,0.0]
heatConductivity = 0.62
particleModel = "../resources/sphere.obj"
fluidVolume = 2.0
timeStep = 0.01
heatCapacity = 4.1790000000000003
Model = [
{particleModelSize=[30,30,30],particleModelOrigin=[0.0,0.0,0.0]},
]
[App.simulationGridFluid]
datafiles = []
cellModel = "../resources/plane.obj"
specificGasConstant = 461.5
heatCapacity = 4.1790000000000003
buoyancyBeta = 0.10000000000000001
buoyancyAlpha = 9.8000000000000007
heatConductivity = 0.62
diffusionCoefficient = 0.001
ambientTemperature = 25.0

[Vulkan]
pathToShaders = "../shaders/"
window = {name="Default scenario (27k particles)",width=1280,height=720}

