[App]
DEBUG = true
outputToFile = true

[App.simulation]
timeStep = 0.0001
gasStiffness = 100.0
viscosityCoefficient = 3.5
fluidVolume = 0.045
fluidDensity = 998.29
particleCount = 2304 #64
particleModelSize =  [12, 16, 12] #[4, 4, 4]
gridOrigin =  [-0.1, -0.6, -0.1]
gridSize = [16, 55, 16] #[8, 8, 8]
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"

[Vulkan]

[Vulkan.window]
name = "VulkanApp"
width = 800
height = 600

[Vulkan.shaders]
vertex = "/home/aka/CLionProjects/VulkanSPH/shaders/shader.vert"
fragment = "/home/aka/CLionProjects/VulkanSPH/shaders/shader.frag"
compute.massDensity = "/home/aka/CLionProjects/VulkanSPH/shaders/SPH/GridSPH/MassDensity.comp"
compute.forces = "/home/aka/CLionProjects/VulkanSPH/shaders/SPH/GridSPH/Forces.comp"


