[App]
DEBUG = true

[App.simulation]
particleCount = 32
particleModel = "/home/kuro/CLionProjects/VulkanApp/resources/sphere.obj"

[Vulkan]

[Vulkan.window]
name = "VulkanApp"
width = 800
height = 600

[Vulkan.shaders]
vertex = "/home/kuro/CLionProjects/VulkanApp/shaders/shader.vert"
fragment = "/home/kuro/CLionProjects/VulkanApp/shaders/shader.frag"
compute = "/home/kuro/CLionProjects/VulkanApp/shaders/test.comp"


