[App]
DEBUG = true
outputToFile = true

[App.simulation]
useNNS = true
timeStep = 0.001
gasStiffness = 10.0
viscosityCoefficient = 3.5
fluidVolume = 0.2
fluidDensity = 998.29
particleCount = 24000 #2304 #64
particleModelSize = [20,60,20] #[12, 16, 12] #[4, 4, 4]
gridOrigin =  [-0.2, -0.1, -0.2]
gridSize = [20, 40, 20] #[8, 8, 8]
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"

[Vulkan]
pathToShaders = "/home/aka/CLionProjects/VulkanSPH/shaders/"

[Vulkan.window]
name = "VulkanApp"
width = 1280
height = 720


