[Vulkan]
pathToShaders = "/home/aka/CLionProjects/VulkanSPH/shaders/"
window = {height=720,width=1280,name="VulkanApp"}
[App]
cameraPos = [-0.27033710479736328,2.6638836860656738,3.1748919486999512]
yaw = -423.80328369140625
pitch = -36.799858093261719
outputToFile = true
DEBUG = true
[App.simulationSPH]
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"
heatConductivity = 0.62
gridOrigin = [0.0,0.0,0.0]
fluidDensity = 998.28999999999996
particleModelSize = [30,30,30]
viscosityCoefficient = 3.5
gridSize = [20,20,20]
gasStiffness = 10.0
heatCapacity = 4.1790000000000003
timeStep = 0.001
particleCount = 27000
fluidVolume = 2.0
useNNS = true
[App.MarchingCubes]
detail = 2

[App.simulationGridFluid]
ambientTemperature = 25.0
cellModel = "/home/aka/CLionProjects/VulkanSPH/resources/plane.obj"


