[App]
DEBUG = true

[App.simulation]
fluidVolume = 0.1
fluidDensity = 1000.0
particleCount = 5000
particleModelSize = [10, 50, 10]
particleModel = "/home/aka/CLionProjects/VulkanSPH/resources/sphere.obj"

[Vulkan]

[Vulkan.window]
name = "VulkanApp"
width = 800
height = 600

[Vulkan.shaders]
vertex = "/home/aka/CLionProjects/VulkanSPH/shaders/shader.vert"
fragment = "/home/aka/CLionProjects/VulkanSPH/shaders/shader.frag"
compute.massDensity = "/home/aka/CLionProjects/VulkanSPH/shaders/SPH/MassDensity.comp"
compute.forces = "/home/aka/CLionProjects/VulkanSPH/shaders/SPH/Forces.comp"


