#version 450

struct ParticleRecord {
    vec4 position;
    vec4 velocity;
};

layout(std430, binding = 0) buffer positionBuffer{
    ParticleRecord particleRecords[];
};

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;
void main() {
    particleRecords[gl_GlobalInvocationID.x].position = particleRecords[gl_GlobalInvocationID.x].position + particleRecords[gl_GlobalInvocationID.x].velocity;
    particleRecords[gl_GlobalInvocationID.x].velocity *= 0.8f;
}
