#version 460


layout(std430, binding = 3) buffer Counter{
    int counter[];
};

layout(std430, binding = 3) buffer Indexes{
    int indexes[];
};

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint myId = gl_GlobalInvocationID.x;

    if(indexes[myId - 1] == indexes[myId])
        indexes[myId] = -1;
    else
        indexes[myId] = counter[myId];

}